# Frozen Model Configuration

model:
  vision_encoder_name: "resnet50"
  language_model_name: "gpt2-large"
  visual_prefix_length: 2
  vision_hidden_dim: 2048
  lm_hidden_dim: 1280

system:
  device: "cuda"
  num_workers: 4
  seed: 42
  fp16: true
  debug_mode: False  #Set to true for testing with small dataset

data:
  train_image_dir: "../conceptual_captions_data"
  train_file: "../conceptual_captions_data/train.jsonl"
  val_image_dir: "../conceptual_captions_data"
  val_file: "../conceptual_captions_data/validation.jsonl"
  image_size: 224
  max_caption_length: 128
  cache_dir: "cache"
  results_dir: "results_attained"
  plots_dir: "plots"

training:
  batch_size: 8
  num_epochs: 3
  learning_rate: 3.0e-4
  weight_decay: 0
  warmup_steps: 1000
  gradient_accumulation_steps: 16
  output_dir: "frozen_outputs"
  checkpoint_dir: "frozen_checkpoints"
